
"use client";

import { useState } from "react";
import PromptInput from "@/components/PromptInput";
import SkillEditor from "@/components/SkillEditor";
import PrivacyModal from "@/components/PrivacyModal";
import { Github, Orbit } from "lucide-react";

const EXAMPLE_SKILL_MD = `---
name: sample-skill
version: 1.0.0
description: A sample skill generated by the architect.
---

# 🎯 Goal
To demonstrate the UI capability of Antigravity Skill Architect.

# 📋 Instructions
1.  **Analyze the Requirement**: Understand the user's intent.
2.  **Generate Code**: Produce high-quality, bug-free code.
3.  **Validate**: Ensure all scenarios are covered.

## 📦 Dependencies
- Next.js 14
- Tailwind CSS
- Lucide React

## 🚀 Usage
\`\`\`bash
npm run dev
\`\`\`
`;

export default function Home() {
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [output, setOutput] = useState("");
  const [showPrivacy, setShowPrivacy] = useState(false);

  const handleGenerate = async () => {
    setIsLoading(true);
    // Simulate AI Latency
    await new Promise((resolve) => setTimeout(resolve, 2000));
    setOutput(EXAMPLE_SKILL_MD);
    setIsLoading(false);
  };

  return (
    <main className="h-screen bg-zinc-950 flex flex-col font-sans overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4 border-b border-zinc-900 bg-zinc-950/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="flex items-center space-x-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-600 to-blue-600 flex items-center justify-center shadow-lg shadow-purple-500/20">
            <Orbit className="w-5 h-5 text-white" />
          </div>
          <span className="font-semibold text-zinc-100 tracking-tight text-lg">
            Antigravity <span className="text-zinc-500 font-normal">Skill Architect</span>
          </span>
        </div>
        <a
          href="#"
          className="text-zinc-500 hover:text-zinc-300 transition-colors flex items-center space-x-2 text-sm"
        >
          <Github className="w-4 h-4" />
          <span>Support</span>
        </a>
      </header>

      {/* Main Split View */}
      <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
        {/* Left Column: Input */}
        <section className="w-full md:w-1/2 border-r border-zinc-900 h-full overflow-y-auto">
          <PromptInput
            input={input}
            setInput={setInput}
            isGenerating={isLoading}
            handleGenerate={handleGenerate}
          />
        </section>

        {/* Right Column: Output */}
        <section className="w-full md:w-1/2 h-full bg-zinc-950/50">
          <SkillEditor
            markdown={output}
            isVisible={!!output}
          />
        </section>
      </div>

      {/* Footer */}
      <footer className="py-2 border-t border-zinc-900/50 bg-zinc-950 text-center z-10">
        <div className="flex flex-col md:flex-row items-center justify-center space-y-1 md:space-y-0 md:space-x-4 text-xs text-zinc-600">
          <span>Antigravity Skill Architect is an unofficial community project. Not affiliated with Google.</span>
          <button
            onClick={() => setShowPrivacy(true)}
            className="text-zinc-500 hover:text-zinc-300 underline underline-offset-2 transition-colors"
          >
            Terms & Privacy
          </button>
        </div>
      </footer>

      <PrivacyModal
        isOpen={showPrivacy}
        onClose={() => setShowPrivacy(false)}
      />
    </main>
  );
}
