"use client";

import { useState, useEffect } from "react";
import PromptInput from "@/components/PromptInput";
import SkillEditor from "@/components/SkillEditor";
import PrivacyModal from "@/components/PrivacyModal";
import HistorySidebar, { HistoryItem } from "@/components/HistorySidebar";
import { Github, Orbit, Clock } from "lucide-react";

const EXAMPLE_SKILL_MD = `---
name: sample-skill
version: 1.0.0
description: A sample skill generated by the architect.
---

# 🎯 Goal
To demonstrate the UI capability of Antigravity Skill Architect.

# 📋 Instructions
1.  **Analyze the Requirement**: Understand the user's intent.
2.  **Generate Code**: Produce high-quality, bug-free code.
3.  **Validate**: Ensure all scenarios are covered.

## 📦 Dependencies
- Next.js 14
- Tailwind CSS
- Lucide React

## 🚀 Usage
\`\`\`bash
npm run dev
\`\`\`
`;

export default function Home() {
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [output, setOutput] = useState("");
  const [showPrivacy, setShowPrivacy] = useState(false);

  // History State
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);

  // Load History
  useEffect(() => {
    const saved = localStorage.getItem("skill_history");
    if (saved) {
      try {
        setHistory(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }
  }, []);

  // Save History Helper
  const saveHistory = (newHistory: HistoryItem[]) => {
    setHistory(newHistory);
    localStorage.setItem("skill_history", JSON.stringify(newHistory));
  };

  const handleGenerate = async (additionalContext?: string) => {
    setIsLoading(true);

    // In a real app, we would use input + additionalContext here.
    if (additionalContext) {
      console.log("Generating with context:", additionalContext);
    }

    // Simulate AI Latency
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const newOutput = EXAMPLE_SKILL_MD;
    setOutput(newOutput);
    setIsLoading(false);

    // Save to History
    const newItem: HistoryItem = {
      id: crypto.randomUUID(),
      timestamp: Date.now(),
      prompt: input,
      output: newOutput,
      techStack: additionalContext ? "Custom Stack" : "Standard", // Simplified for now
    };

    const updatedHistory = [newItem, ...history].slice(0, 10);
    saveHistory(updatedHistory);
  };

  const restoreHistory = (item: HistoryItem) => {
    setInput(item.prompt);
    setOutput(item.output);
  };

  const clearHistory = () => {
    saveHistory([]);
  };

  return (
    <main className="h-screen bg-zinc-950 flex flex-col font-sans overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-4 border-b border-zinc-900 bg-zinc-950/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="flex items-center space-x-3">
          <button
            onClick={() => setShowHistory(true)}
            className="p-2 hover:bg-zinc-900 rounded-lg text-zinc-500 hover:text-purple-400 transition-colors"
            title="History"
          >
            <Clock className="w-5 h-5" />
          </button>

          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-600 to-blue-600 flex items-center justify-center shadow-lg shadow-purple-500/20">
            <Orbit className="w-5 h-5 text-white" />
          </div>
          <span className="font-semibold text-zinc-100 tracking-tight text-lg">
            Antigravity <span className="text-zinc-500 font-normal">Skill Architect</span>
          </span>
        </div>
        <a
          href="https://github.com/alpertas/antigravity-skills-generator"
          target="_blank"
          rel="noopener noreferrer"
          className="text-zinc-500 hover:text-zinc-300 transition-colors flex items-center space-x-2 text-sm"
        >
          <Github className="w-4 h-4" />
          <span>GitHub / Contribute</span>
        </a>
      </header>

      {/* Main Split View */}
      <div className="flex-1 flex flex-col md:flex-row overflow-hidden relative">
        <HistorySidebar
          isOpen={showHistory}
          onClose={() => setShowHistory(false)}
          historyItems={history}
          onRestore={restoreHistory}
          onClear={clearHistory}
        />

        {/* Left Column: Input */}
        <section className="w-full md:w-1/2 border-r border-zinc-900 h-full overflow-y-auto">
          <PromptInput
            input={input}
            setInput={setInput}
            isGenerating={isLoading}
            handleGenerate={handleGenerate}
          />
        </section>

        {/* Right Column: Output */}
        <section className="w-full md:w-1/2 h-full bg-zinc-950/50">
          <SkillEditor
            markdown={output}
            isVisible={!!output}
          />
        </section>
      </div>

      {/* Footer */}
      <footer className="py-2 border-t border-zinc-900/50 bg-zinc-950 text-center z-10">
        <div className="flex flex-col md:flex-row items-center justify-center space-y-1 md:space-y-0 md:space-x-4 text-xs text-zinc-600">
          <span>No Server Storage. Data remains locally in your browser.</span>
          <button
            onClick={() => setShowPrivacy(true)}
            className="text-zinc-500 hover:text-zinc-300 underline underline-offset-2 transition-colors"
          >
            Terms & Privacy
          </button>
        </div>
      </footer>

      <PrivacyModal
        isOpen={showPrivacy}
        onClose={() => setShowPrivacy(false)} 
      />

      {/* Open Source Toast */}
      <div className="fixed bottom-4 right-4 z-50 animate-in slide-in-from-bottom-5 fade-in duration-500">
        <a
          href="https://github.com/alpertas/antigravity-skills-generator"
          target="_blank"
          rel="noreferrer"
          className="flex items-center space-x-3 bg-zinc-900 border border-zinc-800 p-3 rounded-lg shadow-2xl hover:bg-zinc-800 transition-colors group"
        >
          <div className="bg-zinc-800 p-1.5 rounded-md group-hover:bg-zinc-700 transition-colors">
            <Github className="w-4 h-4 text-white" />
          </div>
          <div className="pr-2">
            <p className="text-xs font-semibold text-zinc-200">Projects is Open Source!</p>
            <p className="text-[10px] text-zinc-500">PRs are welcome 🚀</p>
          </div>
        </a>
      </div>
    </main>
  );
}
